vat_rates:
  Austria: 0.20
  Belgium: 0.21
  Bulgaria: 0.20
  Croatia: 0.25
  Cyprus: 0.19
  CzechRepublic: 0.21
  Denmark: 0.25
  Estonia: 0.20
  Finland: 0.24
  France: 0.20
  Germany: 0.19
  Greece: 0.24
  Hungary: 0.27
  Ireland: 0.23
  Italy: 0.22
  Latvia: 0.21
  Lithuania: 0.21
  Luxembourg: 0.17
  Malta: 0.18
  Netherlands: 0.21
  Poland: 0.23
  Portugal: 0.23
  Romania: 0.19
  Slovakia: 0.20
  Slovenia: 0.22
  Spain: 0.21
  Sweden: 0.25