vat_rates:
  AT: 0.20   # Austria
  BE: 0.21   # Belgium
  BG: 0.20   # Bulgaria
  HR: 0.25   # Croatia
  CY: 0.19   # Cyprus
  CZ: 0.21   # Czech Republic
  DK: 0.25   # Denmark
  EE: 0.20   # Estonia
  FI: 0.24   # Finland
  FR: 0.20   # France
  DE: 0.19   # Germany
  GR: 0.24   # Greece
  HU: 0.27   # Hungary
  IE: 0.23   # Ireland
  IT: 0.22   # Italy
  LV: 0.21   # Latvia
  LT: 0.21   # Lithuania
  LU: 0.17   # Luxembourg
  MT: 0.18   # Malta
  NL: 0.21   # Netherlands
  PL: 0.23   # Poland
  PT: 0.23   # Portugal
  RO: 0.19   # Romania
  SK: 0.20   # Slovakia
  SI: 0.22   # Slovenia
  ES: 0.21   # Spain
  SE: 0.25   # Sweden